; number of active and inactive substances
28             26
        ; active substances
1            'Continuity' ;Continuity
2            'cTR1' ;Conservative Tracer Source 1
3            'dTR1' ;Decayable Tracer Source 1
4            'ModTemp' ;Water Temperature
5            'IM1' ;inorganic matter (IM1)
6            'Cd' ;Cadmium (Cd)
7            'Cr' ;Chromium (Cr)
8            'Cu' ;Copper (Cu)
9            'Ni' ;Nickel (Ni)
10           'Pb' ;Lead (Pb)
11           'Zn' ;Zinc (Zn)
12           'dTR1' ;Decayable Tracer Source 1
13           'Tyre1' ;TRWP fraction 1 (D=30 um)
14           'Tyre2' ;TRWP fraction 2 (D=75 um)
15           'Tyre3' ;TRWP fraction 3 (D=125 um)
16           'Tyre4' ;TRWP fraction 4 (D=200 um)
17           'TyreAgg11' ;Aggregate TRWP fr.1 + IM fr.1
18           'TyreAgg12' ;Aggregate TRWP fr.1 + IM fr.2
19           'TyreAgg13' ;Aggregate TRWP fr.1 + IM fr.3
20           'TyreAgg21' ;Aggregate TRWP fr.2 + IM fr.1
21           'TyreAgg22' ;Aggregate TRWP fr.2 + IM fr.2
22           'TyreAgg23' ;Aggregate TRWP fr.2 + IM fr.3
23           'TyreAgg31' ;Aggregate TRWP fr.3 + IM fr.1
24           'TyreAgg32' ;Aggregate TRWP fr.3 + IM fr.2
25           'TyreAgg33' ;Aggregate TRWP fr.3 + IM fr.3
26           'TyreAgg41' ;Aggregate TRWP fr.4 + IM fr.1
27           'TyreAgg42' ;Aggregate TRWP fr.4 + IM fr.2
28           'TyreAgg43' ;Aggregate TRWP fr.4 + IM fr.3
        ; passive substances
29           'IM1S1' ;IM1 in layer S1
30           'IM1S2' ;IM1 in layer S2
31           'CdS1' ;Cd in layer S1
32           'CdS2' ;Cd in layer S2
33           'CrS1' ;Cr in layer S1
34           'CrS2' ;Cr in layer S2
35           'CuS1' ;Cu in layer S1
36           'CuS2' ;Cu in layer S2
37           'NiS1' ;Ni in layer S1
38           'NiS2' ;Ni in layer S2
39           'PbS1' ;Pb in layer S1
40           'PbS2' ;Pb in layer S2
41           'ZnS1' ;Zn in layer S1
42           'ZnS2' ;Zn in layer S2
43           'TAggSed11' ;Sed. aggregate TRWP fr.1 + IM fr.1
44           'TAggSed12' ;Sed. aggregate TRWP fr.1 + IM fr.2
45           'TAggSed13' ;Sed. aggregate TRWP fr.1 + IM fr.3
46           'TAggSed21' ;Sed. aggregate TRWP fr.2 + IM fr.1
47           'TAggSed22' ;Sed. aggregate TRWP fr.2 + IM fr.2
48           'TAggSed23' ;Sed. aggregate TRWP fr.2 + IM fr.3
49           'TAggSed31' ;Sed. aggregate TRWP fr.3 + IM fr.1
50           'TAggSed32' ;Sed. aggregate TRWP fr.3 + IM fr.2
51           'TAggSed33' ;Sed. aggregate TRWP fr.3 + IM fr.3
52           'TAggSed41' ;Sed. aggregate TRWP fr.4 + IM fr.1
53           'TAggSed42' ;Sed. aggregate TRWP fr.4 + IM fr.2
54           'TAggSed43' ;Sed. aggregate TRWP fr.4 + IM fr.3