; number of active and inactive substances
27             26
        ; active substances
1            'Continuity' ;Continuity
2            'cTR1' ;Conservative Tracer Source 1
3            'dTR1' ;Decayable Tracer Source 1
4            'ModTemp' ;Water Temperature
5            'IM1' ;inorganic matter (IM1)
6            'Cd' ;Cadmium (Cd)
7            'Cr' ;Chromium (Cr)
8            'Cu' ;Copper (Cu)
9            'Ni' ;Nickel (Ni)
10           'Pb' ;Lead (Pb)
11           'Zn' ;Zinc (Zn)
12           'Tyre1' ;TRWP fraction 1 (D=30 um)
13           'Tyre2' ;TRWP fraction 2 (D=75 um)
14           'Tyre3' ;TRWP fraction 3 (D=125 um)
15           'Tyre4' ;TRWP fraction 4 (D=200 um)
16           'TyreAgg11' ;Aggregate TRWP fr.1 + IM fr.1
17           'TyreAgg12' ;Aggregate TRWP fr.1 + IM fr.2
18           'TyreAgg13' ;Aggregate TRWP fr.1 + IM fr.3
19           'TyreAgg21' ;Aggregate TRWP fr.2 + IM fr.1
20           'TyreAgg22' ;Aggregate TRWP fr.2 + IM fr.2
21           'TyreAgg23' ;Aggregate TRWP fr.2 + IM fr.3
22           'TyreAgg31' ;Aggregate TRWP fr.3 + IM fr.1
23           'TyreAgg32' ;Aggregate TRWP fr.3 + IM fr.2
24           'TyreAgg33' ;Aggregate TRWP fr.3 + IM fr.3
25           'TyreAgg41' ;Aggregate TRWP fr.4 + IM fr.1
26           'TyreAgg42' ;Aggregate TRWP fr.4 + IM fr.2
27           'TyreAgg43' ;Aggregate TRWP fr.4 + IM fr.3
        ; passive substances
28           'IM1S1' ;IM1 in layer S1
29           'IM1S2' ;IM1 in layer S2
30           'CdS1' ;Cd in layer S1
31           'CdS2' ;Cd in layer S2
32           'CrS1' ;Cr in layer S1
33           'CrS2' ;Cr in layer S2
34           'CuS1' ;Cu in layer S1
35           'CuS2' ;Cu in layer S2
36           'NiS1' ;Ni in layer S1
37           'NiS2' ;Ni in layer S2
38           'PbS1' ;Pb in layer S1
39           'PbS2' ;Pb in layer S2
40           'ZnS1' ;Zn in layer S1
41           'ZnS2' ;Zn in layer S2
42           'TAggSed11' ;Sed. aggregate TRWP fr.1 + IM fr.1
43           'TAggSed12' ;Sed. aggregate TRWP fr.1 + IM fr.2
44           'TAggSed13' ;Sed. aggregate TRWP fr.1 + IM fr.3
45           'TAggSed21' ;Sed. aggregate TRWP fr.2 + IM fr.1
46           'TAggSed22' ;Sed. aggregate TRWP fr.2 + IM fr.2
47           'TAggSed23' ;Sed. aggregate TRWP fr.2 + IM fr.3
48           'TAggSed31' ;Sed. aggregate TRWP fr.3 + IM fr.1
49           'TAggSed32' ;Sed. aggregate TRWP fr.3 + IM fr.2
50           'TAggSed33' ;Sed. aggregate TRWP fr.3 + IM fr.3
51           'TAggSed41' ;Sed. aggregate TRWP fr.4 + IM fr.1
52           'TAggSed42' ;Sed. aggregate TRWP fr.4 + IM fr.2
53           'TAggSed43' ;Sed. aggregate TRWP fr.4 + IM fr.3