dtm:
  data_type: RasterDataset
  driver: rasterio
  uri: hydro/elevtn.tif
  metadata:
    category: topography

my_hydro:
  data_type: RasterDataset
  driver: rasterio
  uri: hydro/{variable}.tif
  metadata:
    category: hydrology

# Forcing data
weather_forcing:
  data_type: RasterDataset
  driver: raster_xarray
  uri: forcing/weather_forcing.nc
  metadata:
    category: meteo

# River data
river_network:
  data_type: GeoDataFrame
  driver: pyogrio
  uri: river/river.gpkg
  metadata:
    category: river
river_manning_mapping:
  data_type: DataFrame
  driver: pandas
  uri: river/river_manning.csv
  metadata:
    category: river
    description: Mapping of stream order to Manning's n roughness coefficient, based on Chow (1959) and Dingman (2015)

# Soil data
soilgrids:
  data_type: RasterDataset
  driver: rasterio
  uri: soil/{variable}.tif
  metadata:
    category: soil
    url_2017: https://files.isric.org/soilgrids/former/2017-03-10/data/
    url_2020: https://files.isric.org/soilgrids/latest/data/

# Land cover data
corine:
  data_type: RasterDataset
  driver: rasterio
  uri: landcover/corine.tif
  metadata:
    category: landuse & landcover
    author: Copernicus / European Environment Agency
    info: landuse parameters based on corine classification for Europe
    resolution: 100m
    url: https://land.copernicus.eu/en/products/corine-land-cover
corine_mapping:
  data_type: DataFrame
  driver: pandas
  uri: landcover/corine.csv
  metadata:
    category: landuse & landcover
    version: 1.0
    legend: https://image.discomap.eea.europa.eu/arcgis/rest/services/Corine/CLC2018_WM/MapServer/legend
lai_corine:
  data_type: DataFrame
  driver: pandas
  uri: landcover/corine_lai.csv
  metadata:
    category: landuse & landcover

# esa_worldcover:
#   data_type: RasterDataset
#   driver: rasterio
#   uri: landcover/esa_worldcover.tif
#   metadata:
#     category: landuse & landcover
#     info: landuse parameters for the world
#     resolution: 10m
#     url: https://esa-worldcover.org/en
# esa_worldcover_mapping:
#   data_type: DataFrame
#   driver: pandas
#   uri: landcover/esa_worldcover.csv
#   metadata:
#     category: landuse & landcover
#     version: 2021
#     legend: https://esa-worldcover.s3.eu-central-1.amazonaws.com/v200/2021/docs/WorldCover_PUM_V2.0.pdf
# lai_esa:
#   data_type: DataFrame
#   driver: pandas
#   uri: landcover/esa_lai.csv
#   metadata:
#     category: landuse & landcover